# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: socialhack.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'socialhack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10socialhack.proto\x12\nsocialhack\"\x07\n\x05\x45mpty\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"j\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x12\x16\n\x0einternal_notes\x18\x06 \x01(\t\"+\n\x08UserList\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.socialhack.User\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa7\x01\n\x0bUserService\x12/\n\x07GetUser\x12\x12.socialhack.UserId\x1a\x10.socialhack.User\x12\x34\n\tListUsers\x12\x11.socialhack.Empty\x1a\x14.socialhack.UserList\x12\x31\n\nDeleteUser\x12\x12.socialhack.UserId\x1a\x0f.socialhack.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'socialhack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_USERID']._serialized_start=41
  _globals['_USERID']._serialized_end=61
  _globals['_USER']._serialized_start=63
  _globals['_USER']._serialized_end=169
  _globals['_USERLIST']._serialized_start=171
  _globals['_USERLIST']._serialized_end=214
  _globals['_ACK']._serialized_start=216
  _globals['_ACK']._serialized_end=238
  _globals['_USERSERVICE']._serialized_start=241
  _globals['_USERSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
